### ISSUE TITLE
关于对比方法KAG和Adapted的一些问题

### ISSUE THREAD

**Issue by rangwang** [LeqsNaN/KEC#1]
您好，想向您请教一下关于您所用对比方法的几个问题

1.请问kag_data文件夹下的数据是如何生成的，如果您能提供生成该数据相应的代码，我将不胜感激。

2.您论文中提到的另一种对比方法Adapted具体是如何实现的？原论文中的数据集对于情感原因似乎是按照span处理的，因此被抽象成了序列标注的任务，但在KEC的对话任务里情感原因的最小粒度为utterance，并且原论文中提到了多任务的方法，我想知道您这部分具体是使用了哪种方法，如果您可以提供给我相应的代码，我将十分感谢。

我的邮箱是916032687@qq.om，谢谢！

**Comment by LeqsNaN** [comment]
hi, rangwang. 你的邮箱不可达. 换了几个邮箱给您发了, 但是都是无法响应或者回退邮件了, 您能提供其他的邮箱地址嘛.
