### ISSUE TITLE
关于dd_data文件夹中dailydialog_dev_processed.pkl文件

### ISSUE THREAD

**Issue by Kausal-Lei** [LeqsNaN/KEC#2]
请问dailydialog_dev_processed.pkl是如何得到的？我好像没有发现对应dailydialog_dev.pkl的处理文件

**Comment by Kausal-Lei** [comment]
还有_know_tokenize.pkl文件好像也没有对应的处理文件

**Comment by Kausal-Lei** [comment]
请问能麻烦上传一下么~

**Comment by LeqsNaN** [comment]
您好, dailydialog_xxx_processed.pkl文件和_know_tokenize.pkl文件的处理是在dataset.py中处理得到的, 在类KnowledgeDataset和BaseDataset的初始化函数中分别进行了 (line 125) `if os.path.exists(processed_knowledge_path)` 和 (line 18)  `if os.path.exists(processed_data_path)` 的判断, 这两个文件要是不存在, 就进行else部分的数据处理. 您可以参考一下else部分的处理代码. 

dailydialog_xxx.pkl的构造 主要就是对[https://github.com/declare-lab/RECCON/tree/main/data/original_annotation](url)中的json文件进行了一些提取处理, 其实代码非常简单. 我看了一下dailydialog_xxx.pkl文件里的数据格式, 用list存储的对话. 然后对话也是list格式, 其中每个语句都是dict格式, 这跟原json文件数据是类似的, 然后存储了六种key: id是语句的在对话中的编号; speaker是对话者编号; utterance是语句的文本; emotion是语句的情绪标签; evidence只有在非中立语句中才有, 它存的是原因语句的id; act是对话行为标签, 这个是我们额外添加的一个标签, 它来自于dailydialog原数据集, 原数据中是有该标注的, 我们根据RECCON中提供的每个对话的编号, 去原数据中查找得到的, 我们原本打算加入预测它的多任务学习的, 但是发现没有效果, 因此它没有用到相关实验中, 不过我们认为可能其他研究者能够更好使用act标签, 所以就没有将其移除. 最开始的数据处理代码太久之前的了, 所以我现在暂时还没找到构造dailydialog_xxx.pkl的相关文件, 如果找到了, 我会第一时间上传的.

**Comment by LeqsNaN** [comment]
```
import json
import pickle


def get_data(data_path):
    conv_data = []
    data = json.load(open(data_path, 'r'))
    for k, v in data.items():
        conv_item = []
        conv = v[0]
        for i, utt in enumerate(conv):
            utt_item = {}
            speaker = utt['speaker']
            utt_item['id'] = i + 1
            utt_item['speaker'] = speaker
            utterance = utt['utterance']
            utt_item['utterance'] = utterance
            emotion = utt['emotion']
            utt_item['emotion'] = emotion
            if 'expanded emotion cause evidence' in utt:
                evidence = utt['expanded emotion cause evidence']
                utt_item['evidence'] = evidence
            conv_item.append(utt_item)
        conv_data.append(conv_item)
    return conv_data


train_data = get_data('dailydialog_train.json')
dev_data = get_data('dailydialog_valid.json')
test_data = get_data('dailydialog_test.json')

pickle.dump(train_data, open('dailydialog_train.pkl', 'wb'))
pickle.dump(dev_data, open('dailydialog_dev.pkl', 'wb'))
pickle.dump(test_data, open('dailydialog_test.pkl', 'wb'))
```
act标签的获取没找到, 但是前面前五个用到了的key的处理如上所示. 如果act标签对您来说不重要的话, 可以直接把他们全部设为 'question' 就行了. 只需要在上述代码中添加`utt_item['act'] = 'question'`即可.

**Comment by Kausal-Lei** [comment]
好的，非常感谢您的回复！
